# Generated by Django 3.2.3 on 2024-06-04 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0004_auto_20240604_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering': ('id',),
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
