# Generated by Django 3.2.3 on 2024-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={
                'ordering': ('author',),
                'verbose_name': 'Корзина покупок',
                'verbose_name_plural': 'Корзины покупок',
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(
                choices=[
                    ('кг', 'Kg'),
                    ('г', 'Gr'),
                    ('мл', 'Ml'),
                    ("по вкусуCOOK'S PREFERENCE", 'Cook Preference'),
                ],
                default="по вкусуCOOK'S PREFERENCE",
                max_length=64,
            ),
        ),
    ]
