# Generated by Django 3.2.3 on 2024-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0006_auto_20240604_1422'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(
                fields=('recipe', 'author'),
                name='unique-together-recipe-author-in-cart',
            ),
        ),
    ]
