# Generated by Django 3.2.3 on 2024-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_shoppingcart_unique-together-recipe-author-in-cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={
                'ordering': ('author',),
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(
                fields=('recipe', 'author'),
                name='unique-together-recipe-author-in-favorite',
            ),
        ),
    ]
