# Generated by Django 3.2.3 on 2024-06-12 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20240612_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Время готовки не может быть меньше 1 минуты'
                    ),
                    django.core.validators.MaxValueValidator(
                        32376, 'Время готовки не может быть больше 24 часов'
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Количество ингридиента не может быть меньше 1'
                    ),
                    django.core.validators.MaxValueValidator(
                        32376,
                        'Количество ингридиента не может быть больше 8192',
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
