# Generated by Django 3.2.3 on 2024-06-12 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20240612_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Время готовки не может быть меньше 1 минуты'
                    ),
                    django.core.validators.MaxValueValidator(
                        32676, 'Время готовки не может быть больше 24 часов'
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Количество ингридиента не может быть меньше 1'
                    ),
                    django.core.validators.MaxValueValidator(
                        32676,
                        'Количество ингридиента не может быть больше 8192',
                    ),
                ]
            ),
        ),
    ]
