# Generated by Django 3.2.3 on 2024-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foodgram_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
