# Generated by Django 3.2.3 on 2024-06-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_user', '0002_alter_foodgramuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={
                'ordering': ('id',),
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
