# Generated by Django 3.2.3 on 2024-06-10 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_user', '0005_auto_20240610_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='is_subscribed',
            field=models.ManyToManyField(
                blank=True,
                related_name='subscribers',
                through='foodgram_user.Subscribe',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
